def error(message):
    print(message)
    exit(1)
